
package com.javaWebserviceClient.wsimport;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "JAXTestService", targetNamespace = "http://server.webservice.javatest.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface JAXTestService {


    /**
     * 
     * @param id
     * @return
     *     returns com.javaWebserviceClient.wsimport.StudentScore
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getStudentScoreById", targetNamespace = "http://server.webservice.javatest.com/", className = "com.javaWebserviceClient.wsimport.GetStudentScoreById")
    @ResponseWrapper(localName = "getStudentScoreByIdResponse", targetNamespace = "http://server.webservice.javatest.com/", className = "com.javaWebserviceClient.wsimport.GetStudentScoreByIdResponse")
    public StudentScore getStudentScoreById(
        @WebParam(name = "id", targetNamespace = "")
        long id);

}
